module gui

import math
import os

fn generated_shader_source_path() string {
	return os.join_path(os.dir(@FILE), 'shaders', 'gui_builtin.glsl')
}

fn generated_shader_header_path() string {
	return os.join_path(os.dir(@FILE), 'shaders', 'gui_builtin.h')
}

fn generated_shader_cmdline() string {
	return 'sokol-shdc --input shaders/gui_builtin.glsl --output shaders/gui_builtin.h --slang glsl410:hlsl4:metal_macos'
}

fn generated_shader_programs() []string {
	return [
		'gui_blur',
		'gui_filter_blur_h',
		'gui_filter_blur_v',
		'gui_filter_color',
		'gui_filter_texture',
		'gui_gradient',
		'gui_image_clip',
		'gui_rounded_rect',
		'gui_shadow',
	]
}

fn generated_shader_sgl_vertex_stages() []string {
	return [
		'gui_rect_vs',
		'gui_shadow_vs',
		'gui_gradient_vs',
		'gui_filter_sgl_vs',
	]
}

fn generated_shader_raw_vertex_stages() []string {
	return [
		'gui_filter_vs',
	]
}

fn read_generated_shader_header() string {
	return os.read_file(generated_shader_header_path()) or { panic(err) }
}

fn read_gui_source(name string) string {
	return os.read_file(os.join_path(os.dir(@FILE), name)) or { panic(err) }
}

fn count_occurrences(haystack string, needle string) int {
	mut count := 0
	mut offset := 0
	for {
		index := haystack.index_after(needle, offset) or { break }
		count++
		offset = index + needle.len
	}
	return count
}

fn normalize_whitespace(src string) string {
	return src.fields().join(' ')
}

fn sanitize_generated_shader_header(src string) string {
	mut lines := []string{}
	for line in src.split_into_lines() {
		if line.contains('sokol-shdc --input') {
			lines << '        ${generated_shader_cmdline()}'
			continue
		}
		lines << line
	}
	return lines.join('\n')
}

fn test_generated_builtin_shader_files_are_committed() {
	assert os.exists(generated_shader_source_path())
	assert os.exists(generated_shader_header_path())
	header := read_generated_shader_header()
	assert header.contains("#version:1# (machine generated, don't edit!)")
	assert header.contains('Generated by sokol-shdc')
}

fn test_generated_builtin_shader_header_cmdline_is_sanitized() {
	header := read_generated_shader_header()
	assert header.contains(generated_shader_cmdline())
	assert !header.contains(os.dir(@FILE))
	assert !header.contains('--input /')
	assert !header.contains('--output /')
}

fn test_generated_builtin_shader_header_has_all_program_descriptors() {
	header := read_generated_shader_header()
	for program in generated_shader_programs() {
		assert header.contains('static inline const sg_shader_desc* ${program}_shader_desc(sg_backend backend)')
	}
}

fn test_generated_builtin_shader_header_has_d3d11_descriptor_coverage() {
	header := read_generated_shader_header()
	program_count := generated_shader_programs().len
	assert header.contains('SG_BACKEND_GLCORE')
	assert header.contains('SG_BACKEND_METAL_MACOS')
	assert count_occurrences(header, 'if (backend == SG_BACKEND_D3D11)') == program_count
	assert count_occurrences(header, 'desc.vs.d3d11_target = "vs_4_0";') == program_count
	assert count_occurrences(header, 'desc.fs.d3d11_target = "ps_4_0";') == program_count
	assert header.contains('gui_rect_vs_source_hlsl4')
	assert header.contains('gui_shadow_vs_source_hlsl4')
	assert header.contains('gui_gradient_vs_source_hlsl4')
	assert header.contains('gui_filter_vs_source_hlsl4')
	assert header.contains('gui_filter_sgl_vs_source_hlsl4')
	assert header.contains('gui_filter_texture_fs_source_hlsl4')
}

fn test_generated_builtin_shader_header_uses_current_glcore_target() {
	header := read_generated_shader_header()
	generated_docs := read_gui_source('shaders/README.md')
	shader_docs := read_gui_source('docs/SHADERS.md')
	normalized_generated_docs := normalize_whitespace(generated_docs)
	normalized_shader_docs := normalize_whitespace(shader_docs)

	assert header.contains('sokol-shdc --input shaders/gui_builtin.glsl --output shaders/gui_builtin.h --slang glsl410:hlsl4:metal_macos')
	assert header.contains('#version 410')
	assert header.contains('gui_rect_vs_source_glsl410')
	assert header.contains('gui_rounded_rect_fs_source_glsl410')
	assert !header.contains('glsl330')
	assert !header.contains('#version 330')

	assert generated_docs.contains('`glsl410` target is intentional')
	assert normalized_generated_docs.contains('Do not rewrite the generated header to `glsl330`')
	assert normalized_generated_docs.contains('runtime custom `Shader.glsl` body format')

	assert shader_docs.contains('Generated built-in shaders are separate from this runtime `Shader` API')
	assert shader_docs.contains('`glsl410` for desktop `SG_BACKEND_GLCORE`')
	assert normalized_shader_docs.contains('GLSL 3.3 contract below applies only to runtime custom `Shader.glsl` bodies')
}

fn test_generated_builtin_shader_header_keeps_sgl_binding_contracts() {
	header := read_generated_shader_header()
	for stage in generated_shader_sgl_vertex_stages() {
		assert header.contains('#define ATTR_${stage}_position (0)')
		assert header.contains('#define ATTR_${stage}_texcoord0 (1)')
		assert header.contains('#define ATTR_${stage}_color0 (2)')
		assert header.contains('#define ATTR_${stage}_psize (3)')
		assert header.contains('#define SLOT_${stage}_params (0)')
	}
	assert count_occurrences(header, 'desc.attrs[3].name = "psize";') == 6
	assert count_occurrences(header, 'desc.attrs[3].sem_name = "TEXCOORD";') == 6
	assert count_occurrences(header, 'desc.attrs[3].sem_index = 3;') == 6
	assert header.contains('desc.vs.source = (const char*)gui_filter_sgl_vs_source_hlsl4;')
	assert header.contains('#define SLOT_tex (0)')
	assert header.contains('#define SLOT_smp (0)')
}

fn test_generated_builtin_shader_header_keeps_raw_filter_binding_contract() {
	header := read_generated_shader_header()
	for stage in generated_shader_raw_vertex_stages() {
		assert header.contains('#define ATTR_${stage}_position (0)')
		assert header.contains('#define ATTR_${stage}_texcoord0 (1)')
		assert header.contains('#define ATTR_${stage}_color0 (2)')
		assert !header.contains('#define ATTR_${stage}_psize (3)')
		assert header.contains('#define SLOT_${stage}_params (0)')
	}
}

fn test_d3d11_custom_shader_guard_returns_before_runtime_source_pipeline() {
	source := read_gui_source('shaders.v')
	guard_index := source.index('custom GLSL/Metal shaders are not supported with -d sokol_d3d11') or {
		panic(err)
	}
	glsl_build_index := source.index('fs_source := build_glsl_fragment(shader.glsl)') or {
		panic(err)
	}
	make_shader_index := source.index('shader: gfx.make_shader(&shader_desc)') or { panic(err) }
	guard_return_index := source.index_after('return pip', guard_index) or { panic(err) }
	assert guard_index < glsl_build_index
	assert guard_index < make_shader_index
	assert guard_return_index < glsl_build_index
	assert guard_return_index < make_shader_index
}

fn test_generated_builtin_shader_header_is_fresh_when_requested() {
	if os.getenv('GUI_CHECK_GENERATED_SHADERS') != '1' {
		return
	}

	tmp_dir := os.join_path(os.temp_dir(), 'gui_builtin_shader_fresh_${os.getpid()}')
	tmp_shader_dir := os.join_path(tmp_dir, 'shaders')
	os.rmdir_all(tmp_dir) or {}
	os.mkdir_all(tmp_shader_dir) or { panic(err) }
	tmp_source := os.join_path(tmp_shader_dir, 'gui_builtin.glsl')
	tmp_header := os.join_path(tmp_shader_dir, 'gui_builtin.h')
	os.cp(generated_shader_source_path(), tmp_source) or { panic(err) }

	cmd := '${os.quoted_path(@VEXE)} shader -l glsl410 -l hlsl4 -l metal_macos ${os.quoted_path(tmp_source)}'
	res := os.execute(cmd)
	assert res.exit_code == 0, res.output

	checked_in := sanitize_generated_shader_header(read_generated_shader_header())
	regenerated := sanitize_generated_shader_header(os.read_file(tmp_header) or { panic(err) })
	assert checked_in == regenerated, 'generated shader header is stale; run `v shader -l glsl410 -l hlsl4 -l metal_macos shaders/gui_builtin.glsl`'
	os.rmdir_all(tmp_dir) or {}
}

fn test_pack_shader_params() {
	// 10.0 px radius -> 40 fixed-point units.
	mut val := pack_shader_params(10.0, 0.0)
	assert val == 163840.0

	// 5.5 px radius, 2.0 px thickness.
	val = pack_shader_params(5.5, 2.0)
	assert val == 90120.0

	// 0 px radius, 10 px thickness.
	val = pack_shader_params(0.0, 10.0)
	assert val == 40.0

	// Reconstruction path mirrors shader decode.
	val = pack_shader_params(25.0, 15.5)
	unpacked_radius := math.floor(val / 4096.0) / 4.0
	unpacked_thickness := math.fmod(val, 4096.0) / 4.0

	assert unpacked_radius == 25.0
	assert unpacked_thickness == 15.5
}

fn test_pack_shader_params_clamps_to_max() {
	val := pack_shader_params(5000.0, 5000.0)
	assert val == 16777215.0
	unpacked_radius := math.floor(val / 4096.0) / 4.0
	unpacked_thickness := math.fmod(val, 4096.0) / 4.0
	assert unpacked_radius == 1023.75
	assert unpacked_thickness == 1023.75
}

fn test_normalize_gradient_stops_for_shader_clamps_and_sorts() {
	stops := [
		GradientStop{
			color: Color{255, 0, 0, 255}
			pos:   1.5
		},
		GradientStop{
			color: Color{0, 0, 255, 255}
			pos:   -0.25
		},
	]
	normalized := normalize_gradient_stops_for_shader(stops)
	assert normalized.len == 2
	assert normalized[0].pos == 0.0
	assert normalized[1].pos == 1.0
	assert normalized[0].color.b == 255
	assert normalized[1].color.r == 255
}

fn test_normalize_gradient_stops_for_shader_resamples_extra_stops() {
	stops := [
		GradientStop{
			color: Color{255, 0, 0, 255}
			pos:   0.0
		},
		GradientStop{
			color: Color{255, 255, 0, 255}
			pos:   0.2
		},
		GradientStop{
			color: Color{0, 255, 0, 255}
			pos:   0.4
		},
		GradientStop{
			color: Color{0, 255, 255, 255}
			pos:   0.6
		},
		GradientStop{
			color: Color{255, 0, 255, 255}
			pos:   0.8
		},
		GradientStop{
			color: Color{0, 0, 255, 255}
			pos:   1.0
		},
	]
	normalized := normalize_gradient_stops_for_shader(stops)
	assert normalized.len == gradient_shader_stop_limit
	assert normalized[0].pos == 0.0
	assert normalized[gradient_shader_stop_limit - 1].pos == 1.0
	assert normalized[gradient_shader_stop_limit - 1].color.b == 255
	assert normalized[gradient_shader_stop_limit - 1].color.r == 0
}

fn test_build_glsl_fragment_uses_packed_radius_decode() {
	src := build_glsl_fragment('frag_color = vec4(1.0);')
	assert src.contains('float radius = floor(params / 4096.0) / 4.0;')
}

fn test_build_metal_fragment_uses_packed_radius_decode() {
	src := build_metal_fragment('float4 frag_color = float4(1.0);')
	assert src.contains('float radius = floor(in.params / 4096.0) / 4.0;')
}
